use  MISDB
go                                           -- Table 24

CREATE TABLE user_engagement_MIS(
id int NOT NULL PRIMARY KEY,
candidate_id int NOT NULL
CONSTRAINT FK_user_engagemnt_mis_candidate_id FOREIGN KEY (candidate_id) REFERENCES Fellowship_Candidates(Id),
Date_Time  datetime2(7)  NOT NULL,
Cpu_Count int NOT NULL,
Cpu_Working_Time float  NOT NULL,
Cpu_idle_Time float NOT NULL,
cpu_percent float NOT NULL,
Usage_Cpu_Count int NOT NULL,
number_of_software_interrupts_since_boot float NOT NULL,
number_of_system_calls_since_boot int NOT NULL,
number_of_interrupts_since_boot int NOT NULL,
cpu_avg_load_over_1_min float NOT NULL,
cpu_avg_load_over_5_min float NOT NULL,
cpu_avg_load_over_15_min float NOT NULL,
system_total_memory BIGINT NOT NULL,
system_used_memory float NOT NULL,
system_free_memory float NOT NULL,
system_active_memory float NOT NULL,
system_inactive_memory float NOT NULL,
system_buffers_memory INT NOT NULL,
system_cached_memory float NOT NULL,
system_shared_memory INT NOT NULL,
system_avalible_memory float NOT NULL,
disk_total_memory BIGINT NOT NULL,
disk_used_memory BIGINT NOT NULL,
disk_free_memory BIGINT NOT NULL,
disk_read_count BIGINT NOT NULL,
disk_write_count BIGINT NOT NULL,
disk_read_bytes BIGINT NOT NULL,
disk_write_bytes BIGINT NOT NULL,
time_spent_reading_from_disk BIGINT NOT NULL,
time_spent_writing_to_disk BIGINT NOT NULL,
time_spent_doing_actual_Input_Output BIGINT NOT NULL,
number_of_bytes_sent BIGINT NOT NULL,
number_of_bytes_received BIGINT  NOT NULL,
number_of_packets_sent BIGINT  NOT NULL,
number_of_packets_recived BIGINT  NOT NULL,
total_number_of_errors_while_receiving BIGINT  NOT NULL,
total_number_of_errors_while_sending BIGINT  NOT NULL,
total_number_of_incoming_packets_which_were_dropped BIGINT  NOT NULL,
total_number_of_outgoing_packets_which_were_dropped BIGINT  NOT NULL,
boot_time nvarchar(50) NOT NULL,
keyboard float  NOT NULL,
mouse int NOT NULL,
technology nvarchar(50) NOT NULL,
files_changed int NOT NULL
);
