use MISDB
go

CREATE TABLE Fellowship_Candidates (
  Id int NOT NULL PRIMARY KEY,
  First_Name varchar(100) NOT NULL,
  Middle_Name varchar(100) DEFAULT NULL,
  Last_Name varchar(100) NOT NULL,
  Email varchar(50) NOT NULL,
  Mobile_Num bigint NOT NULL,
  Hired_City varchar(50) NOT NULL,
  Hired_Date datetime NOT NULL,
  Degree varchar(50) NOT NULL,
  Aggregate_Per float DEFAULT NULL,
  Current_Pincode int DEFAULT NULL,
  Permanent_Pincode int DEFAULT NULL,
  Hired_Lab varchar(20) DEFAULT NULL,
  Attitude_Remark varchar(15) DEFAULT NULL,
  Communication_Remark varchar(15) DEFAULT NULL,
  Knowledge_Remark varchar(15) DEFAULT NULL,
  Birth_Date date NOT NULL,
  Is_Birth_Date_Verified int DEFAULT 0,
  Parent_Name varchar(50) DEFAULT NULL,
  Parent_Occupation varchar(100) NOT NULL,
  Parent_Mobile_Num bigint NOT NULL,
  Parent_Annual_Sal float DEFAULT NULL,
  Local_Addr varchar(255) NOT NULL,
  Permanent_Addr varchar(150) DEFAULT NULL,
  Photo_Path varchar(500) DEFAULT NULL,
  Joining_Date date DEFAULT NULL,
  Candidate_Status varchar(20) NOT NULL,
  Personal_Info_filled int DEFAULT 0,
  Bank_Info_Filled int  DEFAULT 0,
  Educational_Info_Filled int DEFAULT 0,
  Doc_Status varchar(20) DEFAULT NULL,
  Remark varchar(150) DEFAULT NULL,
  Creator_Stamp datetime DEFAULT NULL,
  Creator_User int DEFAULT NULL,
);